references:
  container_node: &container_node
    working_directory: ~/project
    docker:
      - image: circleci/node:10.9.0

version: 2
jobs:
  deploy:
    <<: *container_node
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-v1-{{ .Branch }}-{{ checksum "./web/package.json" }}
            - npm-cache-v1-
      - run:
          name: Install dependencies
          command: |
            cd web
            yarn install
      - run:
          name: Deploy
          command: |
            cd web
            git config --global user.email "yukihirai0505@gmail.com"
            git config --global user.name "Yuki Hirai"
            unset CI
            yarn deploy
      - save_cache:
          key: npm-cache-v1-{{ .Branch }}-{{ checksum "./web/package.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy:
          context: default
          filters:
            branches:
              only:
                - master
